### ISSUE TITLE
Can we add some Run and dependency setup instructions to readme

### ISSUE THREAD

**Issue by simwilso** [redgridone/plasmid#9]
Could we have some run instructions added here for implementing a new feed and integrating it to an app?

In particular I'm trying to have a play and setup an express page that creates and publishes a signal based on some user input on a FE. but not sure how to do it what dependencies I need to add to NPM what code I need to add to my JS etc.

**Comment by willemolding** [comment]
Added [a tasty example](https://github.com/redgridone/plasmid/blob/master/README.md#examples-running-a-plasmid-node) to the README. Does this resolve the issue in your view?

**Comment by simwilso** [comment]
perfect thanks!
